---

- name: Copy mongodb.repo
  copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo
- name: Install mongo
  command: yum install -y mongodb-org-2.6.0 mongodb-org-server-2.6.0 mongodb-org-shell-2.6.0 mongodb-org-mongos-2.6.0 mongodb-org-tools-2.6.0

#todo sudo echo "exclude=mongodb-org,mongodb-org-server,mongodb-org-shell,mongodb-org-mongos,mongodb-org-tools" >> /etc/yum.conf


- name: Push mongo gstore create script
  template: src=gstore.js.j2 dest=/opt/gstore.js mode=0755 owner=root

- name: Start Mongo
  command: service mongod restart

- name: populate gstoredb
  command: mongo {{ gstoredbname }} /opt/gstore.js
