---



- name: Manually create the initial virtualenv
  command: virtualenv --no-site-packages /opt/modwsgi/gstore_v3_env

- name: upgrade setuptools
  command: pip install --upgrade setuptools pip

- name: Install pyramid
  easy_install:
    name=pyramid==1.5.2
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install pytz
  easy_install:
    name=pytz
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install pymongo
  easy_install:
    name=pymongo
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install tilecache
  easy_install:
    name=tilecache
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install soaplib
  easy_install:
    name=soaplib
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install psycopg2
  easy_install:
    name=psycopg2
    virtualenv=/opt/modwsgi/gstore_v3_env
  environment:
    PATH: /usr/pgsql-9.6/bin:{{ ansible_env.PATH }}
- name: Install django-hstore
  easy_install:
    name=django-hstore
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install gdal
  easy_install:
    name=gdal==1.9.0
    virtualenv=/opt/modwsgi/gstore_v3_env
  environment:
    PATH: /usr/local/bin/:{{ ansible_env.PATH }}

- name: Install Pillow
  easy_install:
    name=Pillow
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install xlwt
  easy_install:
    name=xlwt
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install rdflib
  easy_install:
    name=rdflib
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install requests
  easy_install:
    name=requests
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install sqlalchemy
  easy_install:
    name=sqlalchemy==0.9.8
    virtualenv=/opt/modwsgi/gstore_v3_env
- name: Install paste
  easy_install:
    name=paste
    virtualenv=/opt/modwsgi/gstore_v3_env



- name: Copy mapscript.py
  command: cp /usr/local/src/mapserver-6.4.1/build/mapscript/python/mapscript.py /opt/modwsgi/gstore_v3_env/lib/python2.7/site-packages/
  command: cp /usr/local/src/mapserver-6.4.1/build/mapscript/python/_mapscript.so /opt/modwsgi/gstore_v3_env/lib/python2.7/site-packages/_mapscript.so



- name: Create pyramid.wsgi
  command: cp /opt/templates/pyramid.wsgi.template /opt/modwsgi/gstore_v3_env/pyramid.wsgi

- copy: src=apache.template dest=/etc/httpd/conf/httpd.conf

- copy: src=pcreate.sh dest=/opt/pcreate.sh
- command: bash /opt/pcreate.sh

- name: Delete dir
  command: rm -rf /opt/modwsgi/gstore_v3_env/gstore_v3

- name: Creat symlinks
  file: src=/opt/git/gstore_v3 dest=/opt/modwsgi/gstore_v3_env/gstore_v3 state=link


- name: Set permissions on pyramid.wsgi
  command: chmod 755 /opt/modwsgi/gstore_v3_env/pyramid.wsgi
#- name: Enable new site
#  command: a2ensite gstore_v3
- name: Set perms in virutal env
  command: chmod -R g+rwx /opt/modwsgi/gstore_v3_env
- name: Set ownership on virtual env
  command: chown -R {{ sudouser }}:{{ sudouser }} /opt/modwsgi/gstore_v3_env
- name: Copy development.ini
  command: cp /opt/templates/gstore_v3/development.ini /opt/modwsgi/gstore_v3_env/gstore_v3/development.ini
- name: Restart apache
  command: service httpd restart




