#---
# This playbook deploys a gstore app
#
#- hosts: gstore
#   remote_user:ubuntu 
#   sudo:yes
#
---

- hosts: all
  remote_user: '{{ sudouser }}'
  sudo: yes
  roles:
    - inv

- hosts: mongodb
  remote_user: '{{ sudouser }}'
  sudo: yes
  roles:
    - mongodb

- hosts: elasticsearch
  remote_user: '{{ sudouser }}'
  sudo: yes
  roles:
    - elasticsearch

- hosts: postgres
  remote_user: '{{ sudouser }}'
  sudo: yes
  roles:
    - postgres
  vars_prompt:
    - name: "admin_email"
      prompt: "Enter a valid admin e-mail address"
      private: no

- hosts: gstore
  remote_user: '{{ sudouser }}'
  sudo: yes
  roles:
    - gstore
  vars_prompt:
    - name: "git_username"
      prompt: "Enter your github username."
      private: yes

    - name: "git_password"
      prompt: "Enter your github password."
      private: yes

