---

- name: install the latest version of OpenJDK
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: latest

- name: copy elasticsearch-1.1.0.noarch.rpm
  copy: src=elasticsearch-1.1.0.noarch.rpm dest=/usr/local/src/elasticsearch-1.1.0.noarch.rpm
- name: copy dbsetup.sh
  copy: src=dbsetup.sh dest=/usr/local/src/dbsetup.sh
- name: Install elasticsearch
  command: rpm -i /usr/local/src/elasticsearch-1.1.0.noarch.rpm


- name: setup server name
  command: "su -c 'echo node.name: watersheddev >> /etc/elasticsearch/elasticsearch.yml' - root"
- name: setup standalone config
  command: "su -c 'echo cluster.name: watersheddev >> /etc/elasticsearch/elasticsearch.yml' - root"
- name: fix node as local
  command: "su -c 'echo node.local: true >> /etc/elasticsearch/elasticsearch.yml' - root"
- name: set elasticsearch to start automaticly
  command: systemctl enable elasticsearch.service
- name: Startup elasticsearch
  command: service elasticsearch start
- name: Wait for es to start
  wait_for: port=9200 delay=5
- name: Create index and mappings
  command: /usr/local/src/dbsetup.sh
