---


- name: install repo
  command: rpm -ivh https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm


- name: Install PostgreSQL packages
  yum: pkg=$item state=present
  with_items:
    - postgresql96
    - postgresql96-server
    - postgresql96-libs
    - postgresql96-contrib
    - postgresql96-devel


- name: initdb
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb

- name: restart postgres
  service: name=postgresql-9.6 state=restarted

- name: Install PostGIS packages
  yum: pkg=$item state=present
  with_items:
    - epel-release
    - postgis2_96
    - postgis2_96-client


- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

- name: Push pg_hba configuration
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/9.6/data/pg_hba.conf mode=0640 owner=postgres group=postgres
- name: Push postgres configuration
  template: src=postgresql.conf.j2 dest=/var/lib/pgsql/9.6/data/postgresql.conf mode=0644 owner=postgres group=postgres
- name: restart postgres
  service: name=postgresql-9.6 state=restarted

- name: Create gstore3 DB
  command: su -c "createdb {{ gstoredbname }}" - postgres
- name: Create dataone DB
  command: su -c "createdb {{ dataonedbname }}" - postgres
- name: postgis setup
  command: su -c "psql -d {{ gstoredbname }} -f /usr/pgsql-9.6/share/contrib/postgis-2.3/postgis.sql" - postgres
- name: postgis_comments setup 
  command: su -c "psql -d {{ gstoredbname }} -f /usr/pgsql-9.6/share/contrib/postgis-2.3/postgis_comments.sql" - postgres
- name: spatial_ref_sys setup
  command: su -c "psql -d {{ gstoredbname }} -f /usr/pgsql-9.6/share/contrib/postgis-2.3/spatial_ref_sys.sql" - postgres
- name: rtpostgis setup
  command: su -c "psql -d {{ gstoredbname }} -f /usr/pgsql-9.6/share/contrib/postgis-2.3/rtpostgis.sql" - postgres
- name: raster_comments setup
  command: su -c "psql -d {{ gstoredbname }} -f /usr/pgsql-9.6/share/contrib/postgis-2.3/raster_comments.sql" - postgres
- name: topology setup
  command: su -c "psql -d {{ gstoredbname }} -f /usr/pgsql-9.6/share/contrib/postgis-2.3/topology.sql" - postgres
- name: topology_comments setup
  command: su -c "psql -d {{ gstoredbname }} -f /usr/pgsql-9.6/share/contrib/postgis-2.3/topology_comments.sql" - postgres


- name: Push inital gstore sql
  template: src=gstore.sql.j2 dest=/usr/local/src/gstore.sql mode=0740 owner=postgres group=postgres

- name: Push inital gstore structure
  template: src=gstore.struct.sql.j2 dest=/usr/local/src/gstore.struct.sql mode=0740 owner=postgres group=postgres

- name: Push inital dataone structure
  template: src=dataone.struct.sql.j2 dest=/usr/local/src/dataone.struct.sql mode=0740 owner=postgres group=postgres

- name: Push inital gstore structure
  template: src=gstore.inserts.sql.j2 dest=/usr/local/src/gstore.inserts.sql mode=0740 owner=postgres group=postgres


- name: create gstoredata schema and user
  command: su -c "psql -d {{ gstoredbname }} -f /usr/local/src/gstore.sql" - postgres

- name: create gstore structure
  command: su -c "psql -d {{ gstoredbname }} -f /usr/local/src/gstore.struct.sql" - postgres

- name: initial inserts        
  command: su -c "psql -d {{ gstoredbname }} -f /usr/local/src/gstore.inserts.sql" - postgres

- name: create gstore structure
  command: su -c "psql -d {{ dataonedbname }} -f /usr/local/src/dataone.struct.sql" - postgres

